# Generated by Django 3.2.23 on 2023-11-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoco_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.CharField(default='常盤', max_length=200),
            preserve_default=False,
        ),
    ]
