# Generated by Django 3.2.23 on 2023-11-13 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoco_app', '0002_user_area'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
